#!/bin/sh
echo "cleaning..."
rm -rf target project/project/ project/target/ modules/valhalla/target/ modules/valhalla/project/project/ modules/valhalla/project/target/
echo "all temporary files are removed"

